name: 'Report Coverage'
on: 
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pull-requests: write

    steps:
    - uses: actions/checkout@v2
    - uses: oven-sh/setup-bun@v1

    - name: 'Install Deps'
      run: bun install

    - name: 'Test'
      run: bun run coverage

    - name: 'Report Coverage'
      if: github.event_name == 'pull_request'
      uses: davelosert/vitest-coverage-report-action@v2
